nodeLinker: node-modules

# Enable Yarn Berry features while keeping node_modules
enableGlobalCache: true
enableScripts: true

# Configure package extensions for better compatibility
packageExtensions:
  "@expo/metro-config@*":
    peerDependencies:
      "metro": "*"
      "metro-resolver": "*"
